#pragma once
#include "rust/cxx.h"

// Forward declare the structs generated by CXX
struct SlangPrintOpts;

rust::String pickle(rust::Vec<rust::String> sources,
                    rust::Vec<rust::String> include_dirs,
                    rust::Vec<rust::String> defines,
                    SlangPrintOpts options);
