[package]
name = "bender-slang"
version = "0.3.0"
edition = "2024"
description = "Internal bender crate: Rust bindings for the Slang SystemVerilog parser"
license = "Apache-2.0"
authors = ["Tim Fischer <fischeti@iis.ee.ethz.ch>"]
repository = "https://github.com/pulp-platform/bender"
readme = "README.md"
include = [
  "src/**",
  "cpp/**",
  "!cpp/compile_flags.txt",
  "tests/**",
  "CMakeLists.txt",
  "build.rs",
  "README.md",
]

[dependencies]
cxx = "1.0.194"
thiserror = { workspace = true }

[target.'cfg(windows)'.dependencies]
dunce = { workspace = true }

[build-dependencies]
cmake = "0.1.57"
cxx-build = "1.0.194"

[package.metadata.dist]
dist = false
